version: '3.7'
services: 
    listado-productos: 
        container_name: listado-productos
        build: .
        ports: 
            - "5566:5566"
            - "3000:3000"
        volumes: 
            - $PWD:/web
        working_dir: /web
        restart: always
        environment: 
            NODE_ENV: development
        command: npm start