version: '3.7'
services: 
    budget-control: 
        container_name: budget-control
        image: node
        ports: 
            - "5566:5566"
        volumes: 
            - $PWD:/web
        working_dir: /web
        command: npm start