version: '3.7'
services: 
    clima: 
        container_name: clima
        image: node
        ports: 
            - "5566:5566"
        volumes: 
            - $PWD:/web
        working_dir: /web
        command: npm start