version: '3.7'
services: 
    frases-breaking-bad: 
        container_name: frases-breaking-bad
        image: node
        ports: 
            - "5566:5566"
        volumes: 
            - $PWD:/web
        working_dir: /web
        command: npm start