version: '3.7'
services: 
    Buscador-noticias: 
        container_name: Buscador-noticias
        image: node
        ports: 
            - "5566:5566"
        volumes: 
            - $PWD:/web
        working_dir: /web
        command: npm start