version: '3.7'
services: 
    buscador-imagenes: 
        container_name: buscador-imagenes
        image: node
        ports: 
            - "5566:5566"
        volumes: 
            - $PWD:/web
        working_dir: /web
        command: npm start