version: '3.7'
services: 
    patient-manager: 
        container_name: patient-manager
        image: node
        ports: 
            - "5566:5566"
        volumes: 
            - $PWD:/web
        working_dir: /web
        command: npm start