version: '3.7'
services: 
    cotizador-criptomonedas: 
        container_name: cotizador-criptomonedas
        image: node
        ports: 
            - "5566:5566"
        volumes: 
            - $PWD:/web
        working_dir: /web
        command: npm start